### ISSUE TITLE
Error conversion

### ISSUE THREAD

**Issue by jadedragon-mrm** [minghuaw/toy-rpc#13]
Currently I needed to modify `toy-rpc/src/error.rs` in the `0.8.0-alpha.0` version to support the Error types I use in my project like this:

```rust
impl From<anyhow::Error> for Error {
    fn from(err: anyhow::Error) -> Self {
        Self::ExecutionError(err.to_string())
    }
}
```

However, this is more of a temporary fix, because it adds the dependency to the `anyhow` crate in toy-rpc.
Probably a more general approach to convert the error types would be a better idea.

**Comment by minghuaw** [comment]
I haven't found an elegant solution yet. For now, using the generated service impl for the client (#10), I think the best way is to have something like

For the service definition

```rust
// RPC trait definition
#[async_trait]
#[export_trait(impl_for_client)]
pub trait Arith {
    // This example uses `toy_rpc::Error` type, other error types have not been tested
    #[export_method]
    async fn add(&self, args: (i32, i32)) -> Result<i32, toy_rpc::Error>; 
}
```

For the client

```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let client = Client::dial("127.0.0.1:8080").await.unwrap();

    // Not tested yet, but `toy_rpc::Error` implements `std::error::Error` 
    // so this should be convertible to `anyhow::Result` with the `?` operator.
    let sum = Arith::add(&client, (2,3)).await?; 
}
```

For the server implementation

```rust 
pub struct Calculator { }

#[async_trait]
#[export_trait_impl]
impl Arith for Calculator {
    async fn add(&self, args: (i32, i32)) -> Result<i32, toy_rpc::Error> {
        // Conversion into `toy_rpc::Error::ExecutionError` is implemented for all the basic types
        Err("Not Implemented".into())
    }
}
```

**Comment by jadedragon-mrm** [comment]
Ok I will do it like this

**Comment by jadedragon-mrm** [comment]
Currently this code does not compile, because `anyhow::Error` can not be converted to `toy_rpc::Error` without adding the conversion to `toy-rpc/src/error.rs`:

```rust
fn anyhow_fun() -> anyhow::Result<()> {
    anyhow::bail!("error");
}

#[async_trait]
#[export_trait(impl_for_client)]
pub trait Arith {
    #[export_method]
    async fn foo(&self, _args: ()) -> Result<(), toy_rpc::Error>;
}

struct TestImpl {}

#[async_trait]
#[export_trait_impl]
impl Arith for TestImpl {
    async fn foo(&self, _args: ()) -> Result<(), toy_rpc::Error> {
        anyhow_fun()?; // the trait `From<anyhow::Error>` is not implemented for `toy_rpc::Error`
        Ok(())
    }
}
```

**Comment by minghuaw** [comment]
Ideally I want to implement something that is more general than targeting `anyhow::Error`, which I have not found a good solution yet. As a temporary fix, I have added `impl` for conversion from `anyhow::Error` to `toy_rpc::Error`, and `anyhow` is added as an optional feature. So in order to enable this conversion, you will just need to add "anyhow" in the features list of `toy-rpc`. For example `toy-rpc = {version = "0.8.0-alpha.3", features = ["tokio_runtime", "server", "client", "anyhow"]}` 

I have updated the [`tokio_tcp` example](https://github.com/minghuaw/toy-rpc/tree/main/examples/tokio_tcp) where two methods, one with `anyhow::Result<_>` and one with `Result<_, toy_rpc::Error>`, are added to the RPC trait [here](https://github.com/minghuaw/toy-rpc/blob/08e2fab9e3855f4df9f2403963bac19f32057f60/examples/tokio_tcp/src/rpc.rs#L42).  The server implementation of the two methods can be found [here](https://github.com/minghuaw/toy-rpc/blob/08e2fab9e3855f4df9f2403963bac19f32057f60/examples/tokio_tcp/src/bin/server.rs#L28), and the client makes RPC calls on these methods [here](https://github.com/minghuaw/toy-rpc/blob/08e2fab9e3855f4df9f2403963bac19f32057f60/examples/tokio_tcp/src/bin/client.rs#L45)

**Comment by jadedragon-mrm** [comment]
That's perfect! I tried it and it works without issues.
Also being able to directly return `anyhow::Result` is great because it allows the use of macros like `anyhow::bail` and `anyhow::ensure` which I find very useful.
