### ISSUE TITLE
ToyRPC panics 

### ISSUE THREAD

**Issue by Licenser** [minghuaw/toy-rpc#33]
There are a [number of places](https://github.com/minghuaw/toy-rpc/search?q=expect) where ToyRPC panics instead of returning a manageable error. This is somewhat problematic for a library as it removes the option to handle mistakes gracefully and shuts down the surrounding application, making it non-recoverable. Doubly so for a networked system.

It would be nice to change to code to return an `Err` instead of panicing.

**Comment by minghuaw** [comment]
I think the search results are all from examples or tests, except for https://github.com/minghuaw/toy-rpc/blob/0642e4ec9bd76e1b85d01159f5e089a0a8603798/toy-rpc/src/server/mod.rs#L396, which happens when the server handles websocket connection in a separate task (and this is why I didn't make it returning an error).

However, I do believe there are much room for improvement in terms of error handling

**Comment by Licenser** [comment]
Ja, that's exactly the one I ran into :D. Should have paid more attention when checking for me, sorry.

**Comment by minghuaw** [comment]
@Licenser I pulled out a quick fix (037402ec6053984c7f9eb15f96c1ae6d8a893c5f) in ver [0.8.5](https://crates.io/crates/toy-rpc), which is already up on crates.io. It now performs ws handshake in the main task and spawns a separate task after a successful ws connection.

**Comment by Licenser** [comment]
Oh wow, that was fast, thank you so much! you are awesome :D

**Comment by minghuaw** [comment]
Just a quick note. I will pick up the work on version 0.9 after I am done with a major milestone for my other crate (fe2o3-amqp). Just need to stick with 0.8.5 or later a bit longer

**Comment by Licenser** [comment]
No worries, I appriciate the work you put in the crate :)
